In [ ]:
# Generate a 10x4 NumPy array of random scores
import numpy as np
np.random.seed(42)
scores = np.random.randint(0, 101, size=(10, 4))
print(scores)



[[51 92 14 71]
 [60 20 82 86]
 [74 74 87 99]
 [23  2 21 52]
 [ 1 87 29 37]
 [ 1 63 59 20]
 [32 75 57 21]
 [88 48 90 58]
 [41 91 59 79]
 [14 61 61 46]]


In [1]:
# Print average and total scores per student
import numpy as np
np.random.seed(42)
scores = np.random.randint(0, 101, size=(10, 4))

print("Total per student:", scores.sum(axis=1))
print("Average per student:", scores.mean(axis=1))


Total per student: [228 248 334  98 154 143 185 284 270 182]
Average per student: [57.   62.   83.5  24.5  38.5  35.75 46.25 71.   67.5  45.5 ]


In [3]:
# Identify topper (highest total)
import numpy as np
np.random.seed(42)
scores = np.random.randint(0, 101, size=(10, 4))

total_scores = scores.sum(axis=1)
print("Topper: Student", total_scores.argmax() + 1, "with total score", total_scores.max())



Topper: Student 3 with total score 334


In [4]:
# Print highest and lowest scorer per subject
import numpy as np

np.random.seed(42)
scores = np.random.randint(0, 101, size=(10, 4))

print("Highest per subject:", scores.max(axis=0))
print("Lowest per subject:", scores.min(axis=0))


Highest per subject: [88 92 90 99]
Lowest per subject: [ 1  2 14 20]


In [7]:
# Normalize scores and show top 3 normalized students. Range: [0,1]
import numpy as np

np.random.seed(42)
scores = np.random.randint(0, 101, size=(10, 4))

norm = (scores - scores.min(0)) / np.ptp(scores, axis=0)
top3 = np.argsort(norm.sum(1))[-3:][::-1]

print("Top 3 students:", top3 + 1)
print("Normalized scores of top 3:\n", norm[top3])




Top 3 students: [3 8 9]
Normalized scores of top 3:
 [[0.83908046 0.8        0.96052632 1.        ]
 [1.         0.51111111 1.         0.48101266]
 [0.45977011 0.98888889 0.59210526 0.74683544]]
