In [ ]:
# Generate a 10x4 NumPy array of random scores
import numpy as np
np.random.seed(42)
scores = np.random.randint(0, 101, size=(10, 4))
print(scores)



[[51 92 14 71]
 [60 20 82 86]
 [74 74 87 99]
 [23  2 21 52]
 [ 1 87 29 37]
 [ 1 63 59 20]
 [32 75 57 21]
 [88 48 90 58]
 [41 91 59 79]
 [14 61 61 46]]


In [1]:
# Print average and total scores per student
import numpy as np
np.random.seed(42)
scores = np.random.randint(0, 101, size=(10, 4))

print("Total per student:", scores.sum(axis=1))
print("Average per student:", scores.mean(axis=1))


Total per student: [228 248 334  98 154 143 185 284 270 182]
Average per student: [57.   62.   83.5  24.5  38.5  35.75 46.25 71.   67.5  45.5 ]


In [3]:
# Identify topper (highest total)
import numpy as np
np.random.seed(42)
scores = np.random.randint(0, 101, size=(10, 4))

total_scores = scores.sum(axis=1)
print("Topper: Student", total_scores.argmax() + 1, "with total score", total_scores.max())



Topper: Student 3 with total score 334


In [4]:
# Print highest and lowest scorer per subject
import numpy as np

np.random.seed(42)
scores = np.random.randint(0, 101, size=(10, 4))

print("Highest per subject:", scores.max(axis=0))
print("Lowest per subject:", scores.min(axis=0))


Highest per subject: [88 92 90 99]
Lowest per subject: [ 1  2 14 20]


In [7]:
# Normalize scores and show top 3 normalized students. Range: [0,1]
import numpy as np

np.random.seed(42)
scores = np.random.randint(0, 101, size=(10, 4))

norm = (scores - scores.min(0)) / np.ptp(scores, axis=0)
top3 = np.argsort(norm.sum(1))[-3:][::-1]

print("Top 3 students:", top3 + 1)
print("Normalized scores of top 3:\n", norm[top3])




Top 3 students: [3 8 9]
Normalized scores of top 3:
 [[0.83908046 0.8        0.96052632 1.        ]
 [1.         0.51111111 1.         0.48101266]
 [0.45977011 0.98888889 0.59210526 0.74683544]]


In [ ]:
import numpy as np
x=np.array([4,5,6,7,8])


In [1]:
import numpy as np
x=np.array([4,5,6,7,8])
xp=np.power(x,2)
print(xp)

[16 25 36 49 64]


In [ ]:
x=np.array([4,5,6,7,8])
y=np.add(x,2)  #add the value 2
print(y)

[ 6  7  8  9 10]


In [8]:
import numpy as np

x = np.array([5, 3, 6, 7, 8])
a = np.append(x, [9])  # Appending 9 to the array x
print(a)


[5 3 6 7 8 9]


In [ ]:
import numpy as np

x = np.array([5, 3, 6, 7, 8])
a = np.insert(x, 2,1)   # insert 1 at the index 2
print(a)

[5 3 1 6 7 8]


In [12]:
x=np.zeros((2,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
z=np.ones((3,5))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Full

In [ ]:
x=np.full((2,5),7)   # adds the value 7 in all the 2,5 matrice
print(x)

[[7 7 7 7 7]
 [7 7 7 7 7]]


np.ararnge
np.linspace

In [22]:
x=np.arange(2,10,2).reshape(2,2)
print(x)           



[[2 4]
 [6 8]]


In [21]:
#syntax=np.linspace(start,stop,numbers)
r=np.linspace(2,10,2)
print(r)

[ 2. 10.]


In [31]:
scores = np.random.random(6)   # between 0 and 1
print(scores)

[0.00734245 0.83362392 0.77497803 0.71787989 0.41849725 0.88510055]


In [32]:
scores = np.random.randint(1, 100, size=(10, 5))   # 10 rows and 5 columns
print(scores)

[[ 6 22 29 95 43]
 [47 49  5 58 12]
 [19 92 44 94 13]
 [88 31  9 69 20]
 [86 69 67 24 50]
 [54 32 62 12 67]
 [95 74 40 88 48]
 [72 60  5 28 88]
 [ 1 46 32 21  3]
 [64 58 33 79  8]]


In [34]:
scores = np.random.randint(1, 100, 5)   # 10 rows and 5 columns
print(scores)

[58 14 59 41 96]


In [ ]:
d=np.random.uniform(0,10,5)    # generates the number in floating point
print(d)

[5.96909771 0.65451554 3.82810189 8.63198735 7.01175893]
